### ISSUE TITLE
Acess image remote server error problem

### ISSUE THREAD

**Issue by Spatos** [derekhe/msfs2020-map-enhancement#706]
Hello, I'm having issues starting the application for use in the flight simulator. When I click on "Start," some time passes and an error message appears saying the following: "Access remote image server error. Make sure your connection with the remote image server is good. The request was canceled due to the configured HttpClient. Timeout of 10 seconds elapsing." The application version is 8.0.6.0, and I'm using an Ethernet connection. I had the same problem two versions ago, but I managed to resolve it by using Cloudflare Warp, which I think is a VPN. However, now I'm having problems even with this VPN. I use Starlink, if that's relevant.

**Comment by RWTurenne** [comment]
I get the same error with no VPN.  In addition, clicking the Start button a second time  gives this: 
Error
---------------------------
MITM test failed. The modification of the hosts file may not be successful.
---------------------------
OK
version 8.0.5.0 also gives these errors.

**Comment by derekhe** [comment]
Please delete the hosts file and create a new one.
Here is the guide for hosts related issues: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#85-hosts-file-issues

**Comment by Spatos** [comment]
how to create a new one

**Comment by RWTurenne** [comment]
> Please delete the hosts file and create a new one. Here is the guide for hosts related issues: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#85-hosts-file-issues

Did that and it worked but only after rebooting.  Next day got the same errors again.

**Comment by Canadian007-MSFS** [comment]
I have tried all the steps, but this is not working.  App still gives the same error and will not work. Yet, no matter what changes I make, the whole folder gets switched back to Read Only

**Comment by derekhe** [comment]
You should find out if any application or antivirus has hosts protection function turned on.

**Comment by Spatos** [comment]
please derekhe help us solve the problem, so far nothing is fixed.

**Comment by Canadian007-MSFS** [comment]
I am no longer getting this issue with the Google server or the third free option (I forget it's name at the moment). It DOES still seem to happen with BING. I had it a few times with the Google server and the third option at first, but was persistant and tried 2 - 3 times and now no issue.  I am thinking it needs a certain amount of the map data predownloaded before it will launch and that the download may not be happening fast enough to satisfy the app/server parameters and it times out? Just a shot in the dark, but again, no longer any issues with Google or option 3. All I did was multiple attmpts in a row and NOTHING else

Not to concerned with the Bing option as I usually fly low altitude anyways.

**Comment by The-SKunkworx** [comment]
I also began to have this issue once 8.0.7 was installed.  I can connect to Bing with no issues but Google is giving me.... 

"Access remote image server error. Make sure your connection with the remote image server is good.  Response status code does not indicate success: 403 (Forbidden).

I have uninstalled and reinstalled several times making sure to delete all folder.  Virus protection is turned off just to make sure.  Version 8.0.6 was working perfectly.  I had no issues for weeks before this happened.

**Comment by derekhe** [comment]
> I also began to have this issue once 8.0.7 was installed. I can connect to Bing with no issues but Google is giving me....
> 
> "Access remote image server error. Make sure your connection with the remote image server is good. Response status code does not indicate success: 403 (Forbidden)."
> 
> I have uninstalled and reinstalled several times making sure to delete all folder. Virus protection is turned off just to make sure. Version 8.0.6 was working perfectly. I had no issues for weeks before this happened.

https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#89-google-maps-is-not-loading

**Comment by RWTurenne** [comment]
Still getting the same errors on 8.07.  The following is added to my hosts file when I click Start.
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net

**Comment by derekhe** [comment]
It may be beneficial to review your antivirus settings for options related to hosts.

**Comment by RWTurenne** [comment]
I use Windows Defender for antivirus.  I added an exclusion for the hosts file but still get the errors.  Only way I can make it work is delete the hosts file and reboot.  Deleting will not work without rebooting.
